# Generated by Django 3.0.2 on 2020-01-21 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('program', models.CharField(choices=[('01', 'BTech'), ('41', 'MTech'), ('61', 'PhD'), ('21', 'MSc'), ('43', 'MS-R'), ('22', 'MA'), ('02', 'BDes'), ('42', 'MDes'), ('00', 'Error')], max_length=2)),
                ('department', models.CharField(choices=[('01', 'Computer Science & Engineering'), ('02', 'Electronics & Communication Engineering'), ('03', 'Mechanical Engineering'), ('04', 'Civil Engineering'), ('05', 'Design'), ('06', 'Biosciences & Bioengineering'), ('07', 'Chemical Engineering'), ('22', 'Chemical Science & Technology'), ('08', 'Electronics & Electrical Engineering'), ('23', 'Mathematics & Computing'), ('21', 'Engineering Physics'), ('54', 'Rural Technology'), ('41', 'Humanities & Social Sciences'), ('51', 'Centre for Energy'), ('52', 'Centre for Environment'), ('53', 'Centre for Nanotechnology'), ('55', 'Centre for Linguistic Science & Technology'), ('00', 'Error')], max_length=3)),
                ('bio', models.TextField(max_length=1000)),
                ('contact', models.IntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('profile', models.CharField(max_length=30)),
                ('cpi', models.DecimalField(decimal_places=5, max_digits=7)),
                ('experience_tech', models.TextField(max_length=1000)),
                ('experience_hr', models.TextField(max_length=1000)),
                ('experience_tips', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='exps.Profile')),
            ],
        ),
    ]
