# Generated by Django 3.0.1 on 2020-01-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
